name: kashflow_ui
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  kashflow_core:
    path: ../kashflow_core
  package_info_plus: ^4.1.0
  sentry_flutter: ^7.9.0
  window_manager: ^0.3.5

dev_dependencies:
  all_lint_rules_community: ^0.0.31
  envied_generator: ^0.3.0+3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
