include: package:all_lint_rules_community/all.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

 
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/.test_coverage.dart"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"
    # - "analysis_options.yaml"

linter:
  rules:
    always_put_control_body_on_new_line: false
    always_specify_types: false
    avoid_final_parameters: false

    flutter_style_todos: false
    omit_local_variable_types: false
    prefer_double_quotes: false
    prefer_final_parameters: false
    prefer_relative_imports: false
    public_member_api_docs: false
    unnecessary_final: false
    
