name: kashflow
description: This helps users track their finances
publish_to: "none"
version: 0.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  drift: ^2.11.0
  flex_color_picker: ^3.2.2
  flex_color_scheme: ^7.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.3
  flutter_simple_calculator: ^2.2.3
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^14.1.2
  json_annotation: ^4.8.1
  material_color_utilities: ^0.11.1
  money2: ^5.0.0
  package_info_plus: ^8.0.0
  path: ^1.8.3
  path_provider: ^2.0.0
  riverpod_annotation: ^3.0.0-dev.3
  sentry_flutter: ^8.2.0
  shared_preferences: ^2.0.15
  slang: ^3.30.2
  slang_flutter: ^3.30.0
  smooth_page_indicator: ^1.1.0
  sqlite3_flutter_libs: ^0.5.0
  talker_flutter: ^4.0.2
  vlsid: ^1.0.0
  window_manager: ^0.3.0

dependency_overrides:
  intl: ^0.19.0
  material_color_utilities: ^0.11.1

dev_dependencies:
  all_lint_rules_community: ^0.0.31
  build_runner: null
  custom_lint: null
  dart_define: ^2.1.1
  derry: ^1.5.0
  drift_dev: ^2.11.0
  flutter_gen_runner: ^5.3.1
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  icons_launcher: ^2.1.0
  json_serializable: ^6.7.1
  riverpod_generator: ^ 3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  slang_build_runner: ^3.30.0

flutter:
  assets:
    - assets/images/
    - assets/json/
    - assets/svg/
    - assets/i18n/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-Italic-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Noto_Sans/NotoSans-VariableFont_wdth,wght.ttf
    - family: RemixIcons
      fonts:
        - asset: assets/fonts/RemixIcons/RemixIcons.ttf

  uses-material-design: true

flutter_gen:
  output: lib/src/core/gen/
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_logo.png
  color_dark: "#003333"
  image_dark: assets/images/app_logo.png

  android_12:
    image: assets/images/app_logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/app_logo.png
    icon_background_color_dark: "#003333"

  web: true

icons_launcher:
  image_path: "assets/images/launcher_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true

scripts: scripts.yaml
