name: kashflow
description: This helps users track their finances
publish_to: 'none'
version: '0.0.1'

environment:
  sdk: '>=2.18.2 <4.0.0'

dependencies:
  drift: ^2.4.2
  envied: ^0.3.0+1
  flex_color_scheme: ^7.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^7.0.0
  grouped_scroll_view: ^0.0.9+2
  intl: ^0.17.0
  json_annotation: ^4.8.0
  money2: ^3.3.0
  path: ^1.8.2
  path_provider: ^2.0.11
  phosphor_flutter: ^2.0.0
  riverpod_annotation: ^2.0.0
  sentry_flutter: ^7.5.2
  shared_preferences: ^2.0.15
  sqlite3_flutter_libs: ^0.5.12
  talker_flutter: ^2.4.3
  window_manager: ^0.3.0

dev_dependencies:
  all_lint_rules_community: ^0.0.31
  build_runner: ^2.3.3
  custom_lint: ^0.3.2
  drift_dev: ^2.4.1
  envied_generator: ^0.3.0
  flutter_gen_runner: ^5.3.1
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  icons_launcher: ^2.1.0
  json_serializable: ^6.6.1
  riverpod_generator: ^2.0.0
  riverpod_lint: ^1.1.5

flutter:
  assets:
    - assets/images/
    - assets/json/
    - assets/svg/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Nunito/Nunito-VariableFont_wght.ttf
       # - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
       # - asset: assets/fonts/Nunito/Nunito-Light.ttf
       # - asset: assets/fonts/Nunito/Nunito-Regular.ttf
       # - asset: assets/fonts/Nunito/Nunito-Medium.ttf
       # - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
       # - asset: assets/fonts/Nunito/Nunito-Bold.ttf
       # - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
       # - asset: assets/fonts/Nunito/Nunito-Black.ttf
       # - asset: assets/fonts/Nunito/Nunito-ExtraLightItalic.ttf
       # - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
       # - asset: assets/fonts/Nunito/Nunito-Italic.ttf
       # - asset: assets/fonts/Nunito/Nunito-MediumItalic.ttf
       # - asset: assets/fonts/Nunito/Nunito-SemiBoldItalic.ttf
       # - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
       # - asset: assets/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
       # - asset: assets/fonts/Nunito/Nunito-BlackItalic.ttf

    - family: DancingScript
      fonts:
        - asset: assets/fonts/Dancing_Script/DancingScript-VariableFont_wght.ttf

  uses-material-design: true

flutter_gen:
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_logo.png
  color_dark: "#000000"
  image_dark: assets/images/app_logo.png

  android_12:
    image: assets/images/app_logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/app_logo.png
    icon_background_color_dark: "#000000"

  web: true
  android_gravity: fill
  ios_content_mode: scaleToFill
  web_image_mode: contain

icons_launcher:
  image_path: 'assets/images/app_logo.png'
  platforms:
    android:
      adaptive_monochrome_image: 'assets/images/app_logo.png'
      enable: true
    ios:
      enable: true
    web:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true
