name: kashflow_core
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  all_lint_rules_community: ^0.0.31
  flutter_test:
    sdk: flutter

flutter: null
