name: kashflow_core
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  drift: ^2.11.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  money2: ^4.0.0
  path: ^1.8.3
  path_provider: ^2.0.0
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  all_lint_rules_community: ^0.0.31
  build_runner: ^2.4.6
  drift_dev: ^2.11.0
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/json/
