import 'package:flutter/material.dart';

import 'material_scheme.dart';

class MaterialTheme {
  final TextTheme textTheme;

  const MaterialTheme(this.textTheme);

  static MaterialScheme lightScheme() => const MaterialScheme(
        brightness: Brightness.light,
        primary: Color(0xff005e1c),
        surfaceTint: Color(0xff006e22),
        onPrimary: Color(0xffffffff),
        primaryContainer: Color(0xff00872c),
        onPrimaryContainer: Color(0xffffffff),
        secondary: Color(0xff005858),
        onSecondary: Color(0xffffffff),
        secondaryContainer: Color(0xff008080),
        onSecondaryContainer: Color(0xffffffff),
        tertiary: Color(0xff626200),
        onTertiary: Color(0xffffffff),
        tertiaryContainer: Color(0xffffff74),
        onTertiaryContainer: Color(0xff575700),
        error: Color(0xffa50100),
        onError: Color(0xffffffff),
        errorContainer: Color(0xffeb0000),
        onErrorContainer: Color(0xffffffff),
        background: Color(0xfff4fcee),
        onBackground: Color(0xff171d16),
        surface: Color(0xfff9f9f9),
        onSurface: Color(0xff1b1b1b),
        surfaceVariant: Color(0xffe0e3e3),
        onSurfaceVariant: Color(0xff444748),
        outline: Color(0xff747878),
        outlineVariant: Color(0xffc4c7c7),
        shadow: Color(0xff000000),
        scrim: Color(0xff000000),
        inverseSurface: Color(0xff303030),
        inverseOnSurface: Color(0xfff1f1f1),
        inversePrimary: Color(0xff63df6f),
        primaryFixed: Color(0xff80fd88),
        onPrimaryFixed: Color(0xff002105),
        primaryFixedDim: Color(0xff63df6f),
        onPrimaryFixedVariant: Color(0xff005318),
        secondaryFixed: Color(0xff93f2f2),
        onSecondaryFixed: Color(0xff002020),
        secondaryFixedDim: Color(0xff76d6d5),
        onSecondaryFixedVariant: Color(0xff004f4f),
        tertiaryFixed: Color(0xffeaea00),
        onTertiaryFixed: Color(0xff1d1d00),
        tertiaryFixedDim: Color(0xffcdcd00),
        onTertiaryFixedVariant: Color(0xff494900),
        surfaceDim: Color(0xffdadada),
        surfaceBright: Color(0xfff9f9f9),
        surfaceContainerLowest: Color(0xffffffff),
        surfaceContainerLow: Color(0xfff3f3f3),
        surfaceContainer: Color(0xffeeeeee),
        surfaceContainerHigh: Color(0xffe8e8e8),
        surfaceContainerHighest: Color(0xffe2e2e2),
      );

  ThemeData light() => theme(lightScheme().toColorScheme());

  static MaterialScheme lightMediumContrastScheme() => const MaterialScheme(
        brightness: Brightness.light,
        primary: Color(0xff004e16),
        surfaceTint: Color(0xff006e22),
        onPrimary: Color(0xffffffff),
        primaryContainer: Color(0xff00872c),
        onPrimaryContainer: Color(0xffffffff),
        secondary: Color(0xff004b4b),
        onSecondary: Color(0xffffffff),
        secondaryContainer: Color(0xff008080),
        onSecondaryContainer: Color(0xffffffff),
        tertiary: Color(0xff454500),
        onTertiary: Color(0xffffffff),
        tertiaryContainer: Color(0xff797900),
        onTertiaryContainer: Color(0xffffffff),
        error: Color(0xff8c0100),
        onError: Color(0xffffffff),
        errorContainer: Color(0xffeb0000),
        onErrorContainer: Color(0xffffffff),
        background: Color(0xfff4fcee),
        onBackground: Color(0xff171d16),
        surface: Color(0xfff9f9f9),
        onSurface: Color(0xff1b1b1b),
        surfaceVariant: Color(0xffe0e3e3),
        onSurfaceVariant: Color(0xff404344),
        outline: Color(0xff5c6060),
        outlineVariant: Color(0xff787b7c),
        shadow: Color(0xff000000),
        scrim: Color(0xff000000),
        inverseSurface: Color(0xff303030),
        inverseOnSurface: Color(0xfff1f1f1),
        inversePrimary: Color(0xff63df6f),
        primaryFixed: Color(0xff00872c),
        onPrimaryFixed: Color(0xffffffff),
        primaryFixedDim: Color(0xff006b21),
        onPrimaryFixedVariant: Color(0xffffffff),
        secondaryFixed: Color(0xff078282),
        onSecondaryFixed: Color(0xffffffff),
        secondaryFixedDim: Color(0xff006767),
        onSecondaryFixedVariant: Color(0xffffffff),
        tertiaryFixed: Color(0xff797900),
        onTertiaryFixed: Color(0xffffffff),
        tertiaryFixedDim: Color(0xff5f5f00),
        onTertiaryFixedVariant: Color(0xffffffff),
        surfaceDim: Color(0xffdadada),
        surfaceBright: Color(0xfff9f9f9),
        surfaceContainerLowest: Color(0xffffffff),
        surfaceContainerLow: Color(0xfff3f3f3),
        surfaceContainer: Color(0xffeeeeee),
        surfaceContainerHigh: Color(0xffe8e8e8),
        surfaceContainerHighest: Color(0xffe2e2e2),
      );

  ThemeData lightMediumContrast() =>
      theme(lightMediumContrastScheme().toColorScheme());

  static MaterialScheme lightHighContrastScheme() => const MaterialScheme(
        brightness: Brightness.light,
        primary: Color(0xff002908),
        surfaceTint: Color(0xff006e22),
        onPrimary: Color(0xffffffff),
        primaryContainer: Color(0xff004e16),
        onPrimaryContainer: Color(0xffffffff),
        secondary: Color(0xff002727),
        onSecondary: Color(0xffffffff),
        secondaryContainer: Color(0xff004b4b),
        onSecondaryContainer: Color(0xffffffff),
        tertiary: Color(0xff242400),
        onTertiary: Color(0xffffffff),
        tertiaryContainer: Color(0xff454500),
        onTertiaryContainer: Color(0xffffffff),
        error: Color(0xff4e0000),
        onError: Color(0xffffffff),
        errorContainer: Color(0xff8c0100),
        onErrorContainer: Color(0xffffffff),
        background: Color(0xfff4fcee),
        onBackground: Color(0xff171d16),
        surface: Color(0xfff9f9f9),
        onSurface: Color(0xff000000),
        surfaceVariant: Color(0xffe0e3e3),
        onSurfaceVariant: Color(0xff212525),
        outline: Color(0xff404344),
        outlineVariant: Color(0xff404344),
        shadow: Color(0xff000000),
        scrim: Color(0xff000000),
        inverseSurface: Color(0xff303030),
        inverseOnSurface: Color(0xffffffff),
        inversePrimary: Color(0xffb0ffae),
        primaryFixed: Color(0xff004e16),
        onPrimaryFixed: Color(0xffffffff),
        primaryFixedDim: Color(0xff00350c),
        onPrimaryFixedVariant: Color(0xffffffff),
        secondaryFixed: Color(0xff004b4b),
        onSecondaryFixed: Color(0xffffffff),
        secondaryFixedDim: Color(0xff003333),
        onSecondaryFixedVariant: Color(0xffffffff),
        tertiaryFixed: Color(0xff454500),
        onTertiaryFixed: Color(0xffffffff),
        tertiaryFixedDim: Color(0xff2e2e00),
        onTertiaryFixedVariant: Color(0xffffffff),
        surfaceDim: Color(0xffdadada),
        surfaceBright: Color(0xfff9f9f9),
        surfaceContainerLowest: Color(0xffffffff),
        surfaceContainerLow: Color(0xfff3f3f3),
        surfaceContainer: Color(0xffeeeeee),
        surfaceContainerHigh: Color(0xffe8e8e8),
        surfaceContainerHighest: Color(0xffe2e2e2),
      );

  ThemeData lightHighContrast() =>
      theme(lightHighContrastScheme().toColorScheme());

  static MaterialScheme darkScheme() => const MaterialScheme(
        brightness: Brightness.dark,
        primary: Color(0xff63df6f),
        surfaceTint: Color(0xff63df6f),
        onPrimary: Color(0xff00390e),
        primaryContainer: Color(0xff00872c),
        onPrimaryContainer: Color(0xffffffff),
        secondary: Color(0xff76d6d5),
        onSecondary: Color(0xff003737),
        secondaryContainer: Color(0xff007575),
        onSecondaryContainer: Color(0xffffffff),
        tertiary: Color(0xffffffff),
        onTertiary: Color(0xff323200),
        tertiaryContainer: Color(0xffdbdb00),
        onTertiaryContainer: Color(0xff424200),
        error: Color(0xffffb4a8),
        onError: Color(0xff690100),
        errorContainer: Color(0xffeb0000),
        onErrorContainer: Color(0xffffffff),
        background: Color(0xff0e150e),
        onBackground: Color(0xffdde5d8),
        surface: Color(0xff131313),
        onSurface: Color(0xffe2e2e2),
        surfaceVariant: Color(0xff444748),
        onSurfaceVariant: Color(0xffc4c7c7),
        outline: Color(0xff8e9192),
        outlineVariant: Color(0xff444748),
        shadow: Color(0xff000000),
        scrim: Color(0xff000000),
        inverseSurface: Color(0xffe2e2e2),
        inverseOnSurface: Color(0xff303030),
        inversePrimary: Color(0xff006e22),
        primaryFixed: Color(0xff80fd88),
        onPrimaryFixed: Color(0xff002105),
        primaryFixedDim: Color(0xff63df6f),
        onPrimaryFixedVariant: Color(0xff005318),
        secondaryFixed: Color(0xff93f2f2),
        onSecondaryFixed: Color(0xff002020),
        secondaryFixedDim: Color(0xff76d6d5),
        onSecondaryFixedVariant: Color(0xff004f4f),
        tertiaryFixed: Color(0xffeaea00),
        onTertiaryFixed: Color(0xff1d1d00),
        tertiaryFixedDim: Color(0xffcdcd00),
        onTertiaryFixedVariant: Color(0xff494900),
        surfaceDim: Color(0xff131313),
        surfaceBright: Color(0xff393939),
        surfaceContainerLowest: Color(0xff0e0e0e),
        surfaceContainerLow: Color(0xff1b1b1b),
        surfaceContainer: Color(0xff1f1f1f),
        surfaceContainerHigh: Color(0xff2a2a2a),
        surfaceContainerHighest: Color(0xff353535),
      );

  ThemeData dark() => theme(darkScheme().toColorScheme());

  static MaterialScheme darkMediumContrastScheme() => const MaterialScheme(
        brightness: Brightness.dark,
        primary: Color(0xff67e473),
        surfaceTint: Color(0xff63df6f),
        onPrimary: Color(0xff001b04),
        primaryContainer: Color(0xff21a63f),
        onPrimaryContainer: Color(0xff000000),
        secondary: Color(0xff7bdada),
        onSecondary: Color(0xff001a1a),
        secondaryContainer: Color(0xff3a9f9f),
        onSecondaryContainer: Color(0xff000000),
        tertiary: Color(0xffffffff),
        onTertiary: Color(0xff323200),
        tertiaryContainer: Color(0xffdbdb00),
        onTertiaryContainer: Color(0xff212100),
        error: Color(0xffffbaaf),
        onError: Color(0xff370000),
        errorContainer: Color(0xffff5540),
        onErrorContainer: Color(0xff000000),
        background: Color(0xff0e150e),
        onBackground: Color(0xffdde5d8),
        surface: Color(0xff131313),
        onSurface: Color(0xfffbfbfb),
        surfaceVariant: Color(0xff444748),
        onSurfaceVariant: Color(0xffc8cbcc),
        outline: Color(0xffa0a3a4),
        outlineVariant: Color(0xff808484),
        shadow: Color(0xff000000),
        scrim: Color(0xff000000),
        inverseSurface: Color(0xffe2e2e2),
        inverseOnSurface: Color(0xff2a2a2a),
        inversePrimary: Color(0xff005418),
        primaryFixed: Color(0xff80fd88),
        onPrimaryFixed: Color(0xff001603),
        primaryFixedDim: Color(0xff63df6f),
        onPrimaryFixedVariant: Color(0xff004010),
        secondaryFixed: Color(0xff93f2f2),
        onSecondaryFixed: Color(0xff001414),
        secondaryFixedDim: Color(0xff76d6d5),
        onSecondaryFixedVariant: Color(0xff003d3d),
        tertiaryFixed: Color(0xffeaea00),
        onTertiaryFixed: Color(0xff121200),
        tertiaryFixedDim: Color(0xffcdcd00),
        onTertiaryFixedVariant: Color(0xff383800),
        surfaceDim: Color(0xff131313),
        surfaceBright: Color(0xff393939),
        surfaceContainerLowest: Color(0xff0e0e0e),
        surfaceContainerLow: Color(0xff1b1b1b),
        surfaceContainer: Color(0xff1f1f1f),
        surfaceContainerHigh: Color(0xff2a2a2a),
        surfaceContainerHighest: Color(0xff353535),
      );

  ThemeData darkMediumContrast() =>
      theme(darkMediumContrastScheme().toColorScheme());

  static MaterialScheme darkHighContrastScheme() => const MaterialScheme(
        brightness: Brightness.dark,
        primary: Color(0xfff1ffea),
        surfaceTint: Color(0xff63df6f),
        onPrimary: Color(0xff000000),
        primaryContainer: Color(0xff67e473),
        onPrimaryContainer: Color(0xff000000),
        secondary: Color(0xffeafffe),
        onSecondary: Color(0xff000000),
        secondaryContainer: Color(0xff7bdada),
        onSecondaryContainer: Color(0xff000000),
        tertiary: Color(0xffffffff),
        onTertiary: Color(0xff000000),
        tertiaryContainer: Color(0xffdbdb00),
        onTertiaryContainer: Color(0xff000000),
        error: Color(0xfffff9f8),
        onError: Color(0xff000000),
        errorContainer: Color(0xffffbaaf),
        onErrorContainer: Color(0xff000000),
        background: Color(0xff0e150e),
        onBackground: Color(0xffdde5d8),
        surface: Color(0xff131313),
        onSurface: Color(0xffffffff),
        surfaceVariant: Color(0xff444748),
        onSurfaceVariant: Color(0xfff9fbfc),
        outline: Color(0xffc8cbcc),
        outlineVariant: Color(0xffc8cbcc),
        shadow: Color(0xff000000),
        scrim: Color(0xff000000),
        inverseSurface: Color(0xffe2e2e2),
        inverseOnSurface: Color(0xff000000),
        inversePrimary: Color(0xff00320b),
        primaryFixed: Color(0xff90ff95),
        onPrimaryFixed: Color(0xff000000),
        primaryFixedDim: Color(0xff67e473),
        onPrimaryFixedVariant: Color(0xff001b04),
        secondaryFixed: Color(0xff97f7f6),
        onSecondaryFixed: Color(0xff000000),
        secondaryFixedDim: Color(0xff7bdada),
        onSecondaryFixedVariant: Color(0xff001a1a),
        tertiaryFixed: Color(0xffeeee00),
        onTertiaryFixed: Color(0xff000000),
        tertiaryFixedDim: Color(0xffd1d100),
        onTertiaryFixedVariant: Color(0xff171700),
        surfaceDim: Color(0xff131313),
        surfaceBright: Color(0xff393939),
        surfaceContainerLowest: Color(0xff0e0e0e),
        surfaceContainerLow: Color(0xff1b1b1b),
        surfaceContainer: Color(0xff1f1f1f),
        surfaceContainerHigh: Color(0xff2a2a2a),
        surfaceContainerHighest: Color(0xff353535),
      );

  ThemeData darkHighContrast() =>
      theme(darkHighContrastScheme().toColorScheme());

  ThemeData theme(ColorScheme colorScheme) => ThemeData(
        useMaterial3: true,
        brightness: colorScheme.brightness,
        colorScheme: colorScheme,
        textTheme: textTheme.apply(
          bodyColor: colorScheme.onSurface,
          displayColor: colorScheme.onSurface,
        ),
        scaffoldBackgroundColor: colorScheme.background,
        canvasColor: colorScheme.surface,
      );

  List<ExtendedColor> get extendedColors => [];
}

class ExtendedColor {
  final Color seed, value;
  final ColorFamily light;
  final ColorFamily lightHighContrast;
  final ColorFamily lightMediumContrast;
  final ColorFamily dark;
  final ColorFamily darkHighContrast;
  final ColorFamily darkMediumContrast;

  const ExtendedColor({
    required this.seed,
    required this.value,
    required this.light,
    required this.lightHighContrast,
    required this.lightMediumContrast,
    required this.dark,
    required this.darkHighContrast,
    required this.darkMediumContrast,
  });
}

class ColorFamily {
  const ColorFamily({
    required this.color,
    required this.onColor,
    required this.colorContainer,
    required this.onColorContainer,
  });

  final Color color;
  final Color onColor;
  final Color colorContainer;
  final Color onColorContainer;
}
